theme: jekyll-theme-minimal

title: SMO Wiki
description: A beautiful snapshot version of the Wiki brought to you by the <a href="https://smo.leibniz-hbi.de/about">Social Media Observatory at HBI</a>

plugins:
  - jekyll-sitemap
